name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # change if your default branch is different

permissions:
  contents: write  # required for gh-pages deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages  # 👈 CHANGE this to match your GitHub Environment name

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache Next.js build
        uses: actions/cache@v3
        with:
          path: |
            .next/cache
            node_modules
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      - name: Disable Next.js telemetry
        run: npx next telemetry disable

      - name: Install dependencies
        run: npm install

      - name: Create .env.local file
        run: |
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" >> .env.local
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> .env.local

      - name: Build and export static site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
